spring:
  application:
    name: order-ms

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      schema: orders

  profiles:
    active:
      - kafka

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: orders
    database-change-log-table: ORDER_DBCHANGELOG
    database-change-log-lock-table: ORDER_DBCHANGELOGLOCK

  redis: ${REDIS_HOST}

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: ${ZIPKIN_BASE_URL}
    sender:
      type: web
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    redis:
      port: ${REDIS_PORT}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /order-ms/api